name: Cypress Tests

on:
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout rama Pruebas
        uses: actions/checkout@v4
        with:
          ref: Pruebas

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm ci

      - name: Ejecutar Cypress con reporte XML
        run: |
          mkdir -p cypress/results
          npx cypress run \
            --reporter mocha-junit-reporter \
            --reporter-options mochaFile=cypress/results/results-[hash].xml,toConsole=true
        env:
          CYPRESS_BASE_URL: https://nexa-vote-front.onrender.com

      - name: Verificar reportes
        run: ls -R cypress/results

      - name: Subir reportes Cypress
        uses: actions/upload-artifact@v4
        with:
          name: cypress-report
          path: cypress/results/*.xml
          retention-days: 7
